image: debian

before_script:
  - apt update -qq
  - apt install -y -qq python3-pip python3-dev python3-pyqt6 python3-pyqt6.qtsvg

stages:
  - test
  - release
  - deploy

test_debian_testing:
  image: debian:testing
  variables:
    QT_QPA_PLATFORM: "offscreen"
  script:
  - pip3 install --break-system-packages matplotlib numpy pytest
  - mkdir -p /tmp/runtime-pyspreadci
  - export XDG_RUNTIME_DIR=/tmp/runtime-pyspreadci
  - py.test
  only:
  - master
  - development

test_debian_testing_optional_req:
  image: debian:testing
  variables:
    QT_QPA_PLATFORM: "offscreen"
  script:
  - apt install -y -qq r-base r-base-dev
  - pip3 install --break-system-packages matplotlib numpy pytest openpyxl rpy2 py-moneyed python-dateutil enchant plotnine pycel pytest-qt
  - mkdir -p /tmp/runtime-pyspreadci
  - export XDG_RUNTIME_DIR=/tmp/runtime-pyspreadci
  - py.test
  only:
  - master
  - development

## Release to pypi
deploy_pypi:
  stage: release
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  script:
    - echo "$TWINE_USERNAME"
    - apt install -y -qq twine
    - python3 setup.py sdist bdist_wheel
    - python3 -m twine upload --skip-existing dist/*
  only:
    - tags


## api.docs pages at pyspread.gitlab.io/pyspread
pages:
  stage: deploy
  image: debian:stable
  script:
  - apt install -y -qq locales
  - pip3 install --break-system-packages -r apidocs/requirements.txt
  - mkdir public
  - export LC_ALL=C
  - dpkg-reconfigure locales
  - QT_QPA_PLATFORM=offscreen ./apidocs/build_docs.sh
  artifacts:
    paths:
    - public
  only:
  - master
